### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MarlikAlmighty** [hipek8/p6-UNIX-Daemonize#4]
marlik@noutbook:/var/www/mydaemon$ zef --install-to=inst#/home/marlik/.perl6 install UNIX::Daemonize
===> Searching for: UNIX::Daemonize
===> Searching for missing dependencies: Test::When, Test::META
===> Searching for missing dependencies: META6, URI
===> Searching for missing dependencies: JSON::Class, JSON::Fast
===> Searching for missing dependencies: JSON::Marshal, JSON::Unmarshal
===> Searching for missing dependencies: JSON::Name
===> Testing: Test::When:ver<1.001008>
===> Testing [OK] for Test::When:ver<1.001008>
===> Testing: JSON::Fast:ver<0.9.8>
===> Testing [OK] for JSON::Fast:ver<0.9.8>
===> Testing: JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>
===> Testing [OK] for JSON::Name:ver<0.0.2>:auth<github:jonathanstowe>
===> Testing: JSON::Marshal:ver<0.0.13>:auth<github:jonathanstowe>
===> Testing [OK] for JSON::Marshal:ver<0.0.13>:auth<github:jonathanstowe>
===> Testing: JSON::Unmarshal:ver<0.08>
===> Testing [OK] for JSON::Unmarshal:ver<0.08>
===> Testing: JSON::Class:ver<0.0.10>:auth<github:jonathanstowe>
===> Testing [OK] for JSON::Class:ver<0.0.10>:auth<github:jonathanstowe>
===> Testing: META6:ver<0.0.18>:auth<github:jonathanstowe>
===> Testing [OK] for META6:ver<0.0.18>:auth<github:jonathanstowe>
===> Testing: URI:ver<0.1.4>
===> Testing [OK] for URI:ver<0.1.4>
===> Testing: Test::META:ver<0.0.13>:auth<github:jonathanstowe>
# the following may make some diagnostics from the module itself
===> Testing [OK] for Test::META:ver<0.0.13>:auth<github:jonathanstowe>
===> Testing: UNIX::Daemonize:ver<0.0.4>
    # Failed test 'Lockfile should be removed'
    # at t/02-daemon-creates-pidfile-and-cleans-up.t line 19
    # Looks like you failed 1 test of 3
# Failed test 'Pidlock files actually working for daemon and are removed afterwards'
# at t/02-daemon-creates-pidfile-and-cleans-up.t line 5
# Looks like you failed 1 test of 1
Valid lockfile exists
  in sub lockfile-create at /home/marlik/.zef/store/p6-UNIX-Daemonize.git/044a39528a21da78010f26f49d39b24aaf233450/lib/UNIX/Daemonize.pm6 (UNIX::Daemonize) line 164
  in sub daemonize at /home/marlik/.zef/store/p6-UNIX-Daemonize.git/044a39528a21da78010f26f49d39b24aaf233450/lib/UNIX/Daemonize.pm6 (UNIX::Daemonize) line 35
  in block <unit> at t/04-creating-second-daemon.t line 9

    # Failed test at t/04-creating-second-daemon.t line 13
    # Looks like you failed 1 test of 2
# Failed test 'Won't create second daemon'
# at t/04-creating-second-daemon.t line 5
# Looks like you failed 1 test of 1
===> Testing [FAIL]: UNIX::Daemonize:ver<0.0.4>
Aborting due to test failure: UNIX::Daemonize:ver<0.0.4> (use --force-test to override)
  in code  at /opt/rakudo-pkg/share/perl6/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 375
  in method test at /opt/rakudo-pkg/share/perl6/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 353
  in code  at /opt/rakudo-pkg/share/perl6/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 530
  in sub  at /opt/rakudo-pkg/share/perl6/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 527
  in method install at /opt/rakudo-pkg/share/perl6/sources/0061125F96D1E60B6E3B0001A4CB4D4188DF4869 (Zef::Client) line 633
  in sub MAIN at /opt/rakudo-pkg/share/perl6/sources/C360CEB3AF792C33F65155FA82FDB7AB4467EC82 (Zef::CLI) line 152
  in block <unit> at /opt/rakudo-pkg/share/perl6/resources/1063D2A135456C8AB42D605E20DBCF9E4A1C9F3B line 1
  in sub MAIN at /opt/rakudo-pkg/bin/zef line 2
  in block <unit> at /opt/rakudo-pkg/bin/zef line 2

**Comment by MarlikAlmighty** [comment]
The cmd --force help me.

**Comment by hipek8** [comment]
Tests behave strangely under newer rakudos, I'll investigate and try to fix implementation or tests.
